//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baseball_Stats_Keeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int StatID { get; set; }
        public int PlayerID { get; set; }
        public Nullable<int> AtBats { get; set; }
        public Nullable<int> Hits { get; set; }
        public Nullable<int> StrikeOuts { get; set; }
        public Nullable<int> Walks { get; set; }
        public Nullable<int> Singles { get; set; }
        public Nullable<int> Doubles { get; set; }
        public Nullable<int> Triples { get; set; }
        public Nullable<int> Homeruns { get; set; }
        public Nullable<int> RBI { get; set; }
        public Nullable<int> Runs { get; set; }
        public Nullable<int> Average { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
